import { useEffect, useMemo, useState } from "react";
import { Link, useNavigate, useLocation, useParams } from "react-router-dom";
import Layout from "../components/Layout";
import SubConditionTable from "../components/SubConditionTable";
import {
  ConditionIndex,
  StartingPointData,
  StartingPointIndex,
} from "../types";

function AiLabel() {
  const [open, setOpen] = useState(false);
  return (
    <span style={{ position: "relative", display: "inline-block" }}>
      <span
        tabIndex={0}
        onMouseEnter={() => setOpen(true)}
        onMouseLeave={() => setOpen(false)}
        onFocus={() => setOpen(true)}
        onBlur={() => setOpen(false)}
        style={{
          fontSize: "0.7rem",
          fontWeight: 600,
          padding: "0.15rem 0.5rem",
          borderRadius: "0.25rem",
          background: "var(--chip-gray-bg)",
          border: "1px solid var(--chip-gray-border)",
          color: "var(--fg-muted)",
          cursor: "help",
          letterSpacing: "0.02em",
          outline: "none",
          userSelect: "none",
        }}
      >
        AI-generated
      </span>
      {open && (
        <div
          role="tooltip"
          style={{
            position: "absolute",
            top: "calc(100% + 0.4rem)",
            right: 0,
            zIndex: 20,
            width: 280,
            maxWidth: "min(280px, 90vw)",
            background: "var(--warn-bg)",
            border: "1px solid var(--warn-border)",
            borderRadius: "0.5rem",
            padding: "0.75rem 0.9rem",
            color: "var(--fg-secondary)",
            fontSize: "0.8rem",
            fontWeight: 400,
            lineHeight: 1.5,
            boxShadow: "0 4px 12px rgba(0,0,0,0.12)",
            whiteSpace: "normal",
          }}
        >
          The relevance signals and sub-condition rankings on this page were
          generated by AI and have not been reviewed by a medical professional.
          Use them as a starting point for your own research — not as a diagnosis.
        </div>
      )}
    </span>
  );
}

export default function StartingPointPage() {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const location = useLocation();

  const [sp, setSp] = useState<StartingPointIndex | null>(null);
  const [spData, setSpData] = useState<StartingPointData | null>(null);
  const [indexMap, setIndexMap] = useState<Map<string, ConditionIndex>>(new Map());
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    window.scrollTo(0, 0);
  }, [id]);

  useEffect(() => {
    Promise.all([
      fetch("/generated/starting_points/index.json").then((r) => r.json()) as Promise<StartingPointIndex[]>,
      fetch("/generated/index.json").then((r) => r.json()) as Promise<ConditionIndex[]>,
    ])
      .then(([spList, conditions]) => {
        setIndexMap(new Map(conditions.map((c) => [c.id, c])));
        const entry = spList.find((s) => s.id === id);
        if (!entry) { setError(`Unknown starting point: ${id}`); return; }
        setSp(entry);
        if (entry.has_signals) {
          return fetch(`/generated/starting_points/${entry.id}.json`)
            .then((r) => r.json())
            .then(setSpData);
        }
      })
      .catch((e) => setError(e.message));
  }, [id]);

  const subConditionRows = useMemo(() => {
    if (!sp || indexMap.size === 0) return [] as ConditionIndex[];
    return sp.sub_conditions
      .map((sc) => indexMap.get(sc.id))
      .filter((c): c is ConditionIndex => !!c);
  }, [sp, indexMap]);

  const probabilityById = useMemo(() => {
    const map: Record<string, number> = {};
    for (const sc of sp?.sub_conditions ?? []) map[sc.id] = sc.probability;
    return map;
  }, [sp]);

  const affinities = useMemo(
    () =>
      (sp?.sub_conditions ?? []).map((sc) => ({
        sub_condition_id: sc.id,
        patterns: sc.patterns,
      })),
    [sp],
  );

  const signals = spData?.sections.sub_condition_signals;

  return (
    <Layout>
      <div style={{ maxWidth: 880, margin: "1rem auto", padding: "0 1rem" }}>
        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
          {location.key !== "default" ? (
            <button
              onClick={() => { window.scrollTo(0, 0); navigate(-1); }}
              style={{ fontSize: "0.875rem", color: "var(--fg-muted)", background: "none", border: "none", padding: 0, cursor: "pointer" }}
            >
              ← Back
            </button>
          ) : (
            <Link to="/" style={{ fontSize: "0.875rem", color: "var(--fg-muted)", textDecoration: "none" }}>
              ← All conditions
            </Link>
          )}
          <AiLabel />
        </div>

        {error && <p style={{ color: "var(--danger)", marginTop: "1rem" }}>{error}</p>}

        {sp && (
          <div style={{ margin: "1rem 0 1.5rem" }}>
            <h1 style={{ fontSize: "1.5rem", fontWeight: 700, marginBottom: "0.25rem", color: "var(--fg)" }}>
              {sp.full_label || sp.label}
            </h1>
            {sp.kind === "syndrome" && sp.condition_id && (
              <p style={{ fontSize: "0.85rem", margin: "0.25rem 0 0.75rem" }}>
                <Link to={`/condition/${sp.condition_id}`} style={{ color: "var(--link)", textDecoration: "none" }}>
                  Learn about {sp.label} the condition →
                </Link>
              </p>
            )}
            {sp.intro && (
              <p style={{
                fontSize: "1.1rem",
                lineHeight: 1.65,
                color: "var(--fg)",
                marginTop: "0.75rem",
              }}>
                {sp.intro}
              </p>
            )}
          </div>
        )}

        {sp && subConditionRows.length > 0 && (
          <div style={{ margin: "0 0 2rem" }}>
            <h2 style={{ fontSize: "0.95rem", fontWeight: 700, textTransform: "uppercase", letterSpacing: "0.05em", color: "var(--fg-secondary)", margin: "0 0 1rem" }}>
              Investigate which underlying conditions fit you
            </h2>
            <SubConditionTable
              rows={subConditionRows}
              probabilityById={probabilityById}
              symptomPatterns={sp.symptom_patterns}
              subConditionAffinities={affinities}
              signalsByConditionId={signals}
            />
          </div>
        )}

        {sp && subConditionRows.length === 0 && !error && (
          <p style={{ color: "var(--fg-muted)", fontSize: "0.9rem" }}>
            This starting point has no sub-conditions yet.
          </p>
        )}
      </div>
    </Layout>
  );
}
